title="System Config File"

[Server]
host = ":1234"
serverKeyPath="./secure/server.key"
serverCertificatePath="./secure/server.crt"

[Authentication]
privateKeyPath = "./secure/app.rsa"
publicKeyPath  = "./secure/app.rsa.pub"
tokenDuration = 720
expireOffset  = 3600

[Log]
logPath="./log/matrix.log"

[MongoDB]
host = "127.0.0.1"

[NSQ]
host = "127.0.0.1:4150"

[Redis]
host = "127.0.0.1:6379"
# maxidle 没有redis连接时依然保持的连接数
maxidle = 1
# maxactive 最大激活的连接数
maxactive = 10
# 最大空闲等待时间，超过此时间连接关闭
idletimeout = 100

[Qiniu]
accessKey="2zSLXJ0NJnMoZYt7ZrR8cMMlxPVVCpHJBJY6zbNN"
secretKey="fKP65ZZ-IlIX3mCrrQQ7PD0kzPqJmQJEhkzrgXad"